# Generated by Django 3.1 on 2020-08-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodItem',
            new_name='ProductItem',
        ),
    ]
